# Generated by Django 3.1.7 on 2021-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Postal_address', models.TextField()),
                ('Personal_Address', models.TextField()),
                ('City', models.CharField(choices=[('ND', 'NEW DELHI'), ('MI', 'MUMBAI'), ('GA', 'GOA'), ('TN', 'TAMILNADU'), ('KL', 'KERALA')], max_length=2)),
                ('Course', models.CharField(choices=[('PS', 'PLAY SCHOOL'), ('PG', 'PRE-KG'), ('FS', 'FIRST STANDARD')], max_length=2)),
                ('Pincode', models.IntegerField(max_length=6)),
                ('EmailID', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('MobileNO', models.IntegerField(max_length=10)),
            ],
        ),
    ]
