# Generated by Django 3.1.7 on 2021-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Sex',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], default=0, max_length=6),
            preserve_default=False,
        ),
    ]
