# Generated by Django 3.1.7 on 2021-03-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_destination_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Name',
            new_name='Student_Name',
        ),
    ]
