# Generated by Django 3.1.7 on 2021-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20210319_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='City',
            field=models.CharField(choices=[('ND', 'NEW DELHI'), ('MI', 'MUMBAI'), ('GA', 'GOA'), ('TN', 'TAMILNADU'), ('KL', 'KERALA')], max_length=225),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Course',
            field=models.CharField(choices=[('PS', 'PLAY SCHOOL'), ('PG', 'PRE-KG'), ('FS', 'FIRST STANDARD')], max_length=225),
        ),
        migrations.AlterField(
            model_name='destination',
            name='MobileNO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Sex',
            field=models.CharField(choices=[('male', 'male'), ('famale', 'female')], default='male', max_length=10),
        ),
    ]
