# Generated by Django 3.1.7 on 2021-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210319_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='MobileNO',
            field=models.IntegerField(max_length=50),
        ),
    ]
