# Generated by Django 3.1.7 on 2021-03-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20210319_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='MobileNO',
            field=models.IntegerField(),
        ),
    ]
